/* **********************************************************************
                              SD_DEFS.H
   v1.0
   Основные определения, для всех программ проекта StarDict.
   (c) В.Перов.
********************************************************************** */

#define     txtHelpFileName             "stardict.hlp"

#define     idHelp              7110

// Имя файла, хранящего опции для StarDict.
#define     txtIniFileName              "stardict.ini"
// *** Секции файла опций :
// Секция свойств приложения:
#define     txtIniSectionAppl           "StarDict"
#define     txtIniSectionAppl_Inst           "InstLeft"
#define     txtIniSectionAppl_UN             "UserName"
#define     txtIniSectionAppl_UNcoded        "Fore"
#define     txtIniSectionAppl_RN             "RegNum"
#define     txtIniSectionAppl_RNcoded        "Back"
#define     txtIniSectionAppl_Lang           "Language"
#define     txtIniSectionAppl_AR             "ARun"
#define     txtIniSectionAppl_AO             "AOpen"
// Секция размера и положения на экране:
#define     txtIniSectionSize           "Size"
#define     txtIniSectionSize_Max          "Max"
#define     txtIniSectionSize_X            "X"
#define     txtIniSectionSize_Y            "Y"
#define     txtIniSectionSize_W            "Width"
#define     txtIniSectionSize_H            "Height"
// Секция описания шрифтов окон ссылок:
#define     txtIniSectionFont           "Font"
#define     txtIniSectionFont_Face         "Face"
#define     txtIniSectionFont_Charset      "Charset"
#define     txtIniSectionFont_Size         "Point"
#define     txtIniSectionFont_Color        "Color"
#define     txtIniSectionFont_ColorLink    "ColorLink"
#define     txtIniSectionFont_ColorKeyword "ColorKeyw"
#define     txtIniSectionFont_BK           "BK"
#define     txtIniSectionFont_Tips         "Tips"

