#define UP    1072
#define DOWN  1080
#define LEFT  1075
#define RIGHT 1077
#define DEL   1083
#define HOME  1071
#define END   1079
#define INS   1082
#define PGUP  1073
#define PGDN  1081
#define TAB      9
#define ENTER   13
#define ESC     27
#define BKSPACE  8
#define SPACE   32

#define CTRL_LEFT    1115
#define CTRL_UP      1141
#define CTRL_RIGHT   1116
#define CTRL_DOWN    1145
#define CTRL_INS     1146
#define CTRL_DEL     1147
#define CTRL_TAB     1148
#define CTRL_BKSPACE  127

#define F1       1059
#define F2       1060
#define F3       1061
#define F4       1062
#define F5       1063
#define F6       1064
#define F7       1065
#define F8       1066
#define F9       1067
#define F10      1068

#define CTRL_F1  1094
#define CTRL_F2  1095
#define CTRL_F3  1096
#define CTRL_F4  1097
#define CTRL_F5  1098
#define CTRL_F6  1099
#define CTRL_F7  1100
#define CTRL_F8  1101
#define CTRL_F9  1102
#define CTRL_F10 1103

#define CTRL_A      1
#define CTRL_C      3
#define CTRL_D      4
#define CTRL_E      5
#define CTRL_F      6
#define CTRL_G      7
#define CTRL_K     11
#define CTRL_N     14
#define CTRL_S     19
#define CTRL_T     20
 
#define ALT_F1   1104

#define ALT_A    1046
#define ALT_C    1030
#define ALT_D    1032
#define ALT_E    1018
#define ALT_X    1045

#define MENU_ENTER  2000

#define SH_UP      56
#define SH_DOWN    50
#define SH_LEFT    52
#define SH_RIGHT   54
#define SH_DEL     46
#define SH_TAB   1015

#define D0         48
#define D1         49
#define D2         50
#define D3         51
#define D4         52
#define D5         53
#define D6         54
#define D7         45
#define D8         56
#define D9         57
