/* ***********************************************************************
                               INSTDEF.H
    v1.0
    Содержит константы, ассоциированные со всеми ресурсами StarDict.
    (c) Перов В.
*********************************************************************** */

#define bmpTriangle        50
#define bmpSD              55
#define bmpSDmono          56

#define icoInstall         81

#define cmDoAllWork      1000
#define cmQuit           1001

#define dlgAskDriveLetter    400
#define dlgAskLang           401
#define dlgAskInfo           402
#define dlgPlans             403
#define dlgFinish            404
#define dlgCopying           405

#define idRussianLang        101
#define idEnglishLang        102
#define idDriveA             103
#define idDriveB             104
#define idUserName           105
#define idSDDirectory        106
#define idGroupName          107
#define idNumInst            108
#define idRegNum             109

